version: '3'
services:
  web:
    image: fray23/trade_bin:web
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - test_data:/code/flaskr/db

volumes:
  test_data:
